version: '3.3'
services:
  bikersdb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - my-db:/var/lib/mysql
  frontend:
    image: ghcr.io/rensvgemert/s3-ip-frontend_bikers:master
    restart: always
    ports: 
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
  backend: 
    depends_on:
      - bikersdb
    image: ghcr.io/rensvgemert/s3-ip-backend:master
    restart: always
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://bikersdb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    depends_on:
      - bikersdb
# Names our volume
volumes:
  my-db:
