version: '3.3'
services:
  bikersdb:
    image: mysql
    networks:
      - bikers-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=bikersdb
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - my-db:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: bikersdb
      PMA_USER: root
      PMA_PORT: "3306"
      PMA_PASSWORD: my-pw
    ports:
      - "8081:80"

  frontend:
    image: ghcr.io/rensvgemert/s3-ip-frontend_bikers:master
    restart: always
    ports: 
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT

  backend: 
    image: ghcr.io/rensvgemert/s3-ip-backend:master
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - bikers-network
    depends_on:
      - bikersdb
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://bikersdb/bikersdb",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
# Names our volume
volumes:
  my-db:

networks:
  bikers-network: 
